version: '3.8'

services:
  fastify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # Server Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - HOST=${HOST:-0.0.0.0}
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      
      # Email Configuration
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SECURE=${EMAIL_SECURE:-false}
      
      # Cloudinary Configuration
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      
      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS:-true}
      
      # Swagger Configuration
      - SWAGGER_HOST=${SWAGGER_HOST:-localhost:3001}
      - SWAGGER_SCHEMES=${SWAGGER_SCHEMES:-http}
      
      # Application Specific
      - APP_NAME=${APP_NAME:-Fastify API}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - APP_DESCRIPTION=${APP_DESCRIPTION:-Fastify API with JWT, PostgreSQL and more}
      
      # File Upload Configuration
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT:-5}
      
      # Rate Limiting (if needed)
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-900000}
      
      # Puppeteer Configuration
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--no-first-run,--no-zygote,--disable-gpu
    
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    
    networks:
      - fastify-network
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  fastify-network:
    driver: bridge